"""Editor — stitch the short_drama clips into the final film.

Reuses the proven two-pass editor from sdk/providers/ffmpeg.py:
  Pass 1: blend_clips_with_xfade — re-encodes with 0.1s cross-dissolve at
          every cut to absorb codec-boundary flicker + audio clicks.
  Pass 2: overlay_music — outro music sting under the final 2 seconds, with
          stream-copy video so lip sync stays intact.

Then optionally appends an outro card (text on solid background) after
the music overlay. Card is rendered standalone via ffmpeg lavfi + drawtext
and concatenated last.

Difference from panel_debate: no separate VO overlay (Seedance native audio
already in clips), no ticker, no channel bug — this is a film, not broadcast.
"""
from __future__ import annotations

import logging
import os
import subprocess
import tempfile
import uuid
from typing import Any

from ....sdk.providers.ffmpeg import (
    _has_audio_stream,
    blend_clips_with_xfade,
    download_file,
    overlay_music,
    probe_duration,
)

log = logging.getLogger(__name__)


def _has_drawtext() -> bool:
    try:
        r = subprocess.run(
            ["ffmpeg", "-hide_banner", "-filters"],
            capture_output=True, text=True, check=False,
        )
    except FileNotFoundError:
        return False
    return " drawtext " in r.stdout


def _escape_drawtext(text: str) -> str:
    return (
        text.replace("\\", "\\\\")
        .replace(":", "\\:")
        .replace("'", "\\'")
        .replace("%", "\\%")
    )


def _render_outro_card(
    text: str, duration_s: float, width: int, height: int, fps: int, out_path: str
) -> None:
    """Render an animated title card.

    Animation timeline (Pixar-flavored title appear):
      t=0.0..0.4s   black hold
      t=0.4..1.6s   title fades in with slight scale-up
      t=1.6..end    title held at full opacity

    Implementation uses drawtext's `alpha` expression (time-based) plus
    `fontsize` expression for the scale-up. If the ffmpeg build lacks
    drawtext we fall back to a static black hold (still a valid clip).
    Output has silent stereo audio so concat with the music-overlay
    output works without re-mux."""
    if _has_drawtext() and text:
        safe = _escape_drawtext(text.upper())
        target_size = max(60, int(height * 0.075))
        # Fade-in window starts at 0.4s, finishes at 1.6s. Scale eases from
        # 0.65 → 1.0 of the target font size over the same window.
        alpha_expr = "if(lt(t,0.4),0,if(lt(t,1.6),(t-0.4)/1.2,1))"
        size_expr = (
            f"if(lt(t,0.4),{int(target_size*0.65)},"
            f"if(lt(t,1.6),"
            f"{int(target_size*0.65)}+({target_size}-{int(target_size*0.65)})*(t-0.4)/1.2,"
            f"{target_size}))"
        )
        vfilter = (
            f"color=c=black:s={width}x{height}:r={fps}:d={duration_s},"
            f"drawtext=text='{safe}':fontcolor=white:"
            f"fontsize='{size_expr}':"
            f"alpha='{alpha_expr}':"
            f"x=(w-tw)/2:y=(h-th)/2"
        )
    else:
        vfilter = f"color=c=black:s={width}x{height}:r={fps}:d={duration_s}"

    cmd = [
        "ffmpeg", "-y", "-hide_banner", "-loglevel", "error",
        "-f", "lavfi", "-i", vfilter,
        "-f", "lavfi", "-t", f"{duration_s}",
        "-i", "anullsrc=r=48000:cl=stereo",
        "-shortest",
        "-c:v", "libx264", "-preset", "veryfast", "-crf", "20",
        "-pix_fmt", "yuv420p",
        "-c:a", "aac", "-b:a", "192k", "-ar", "48000", "-ac", "2",
        "-movflags", "+faststart",
        out_path,
    ]
    result = subprocess.run(cmd, capture_output=True, text=True)
    if result.returncode != 0:
        raise RuntimeError(
            f"outro card render failed (exit {result.returncode}):\n"
            f"{result.stderr[-600:]}"
        )


def _apply_watermark(in_path: str, out_path: str, text: str = "Generated by pixshort.live") -> None:
    """Stamp a small bottom-right watermark on every frame of `in_path`.
    Re-encodes video; audio is stream-copied (lip sync preserved). If the
    ffmpeg build lacks drawtext, falls back to a clean stream copy."""
    if not _has_drawtext():
        cmd = [
            "ffmpeg", "-y", "-hide_banner", "-loglevel", "error",
            "-i", in_path, "-c", "copy",
            "-movflags", "+faststart", out_path,
        ]
        result = subprocess.run(cmd, capture_output=True, text=True)
        if result.returncode != 0:
            raise RuntimeError(f"watermark passthrough failed: {result.stderr[-400:]}")
        return

    safe = _escape_drawtext(text)
    # Bottom-right corner with a 24px margin. Subtle white-on-translucent
    # so it's visible against both bright sets and dark night scenes.
    vf = (
        f"drawtext=text='{safe}':"
        f"fontsize=20:fontcolor=white@0.85:"
        f"box=1:boxcolor=black@0.45:boxborderw=6:"
        f"x=w-tw-24:y=h-th-24"
    )
    cmd = [
        "ffmpeg", "-y", "-hide_banner", "-loglevel", "error",
        "-i", in_path,
        "-vf", vf,
        "-c:v", "libx264", "-preset", "veryfast", "-crf", "20",
        "-pix_fmt", "yuv420p",
        "-c:a", "copy",
        "-movflags", "+faststart",
        out_path,
    ]
    result = subprocess.run(cmd, capture_output=True, text=True)
    if result.returncode != 0:
        raise RuntimeError(
            f"watermark ffmpeg failed (exit {result.returncode}):\n"
            f"{result.stderr[-600:]}"
        )


def _concat(clips: list[str], out_path: str) -> None:
    """Concat with re-encode (concat demuxer + -c copy fails when codec
    params drift between sources, which they do between blend output and
    the synthesized outro card)."""
    list_path = out_path + ".list"
    with open(list_path, "w") as f:
        for c in clips:
            f.write(f"file '{c}'\n")
    cmd = [
        "ffmpeg", "-y", "-hide_banner", "-loglevel", "error",
        "-f", "concat", "-safe", "0", "-i", list_path,
        "-c:v", "libx264", "-preset", "veryfast", "-crf", "20",
        "-pix_fmt", "yuv420p",
        "-c:a", "aac", "-b:a", "192k", "-ar", "48000", "-ac", "2",
        "-movflags", "+faststart",
        out_path,
    ]
    result = subprocess.run(cmd, capture_output=True, text=True)
    if result.returncode != 0:
        raise RuntimeError(
            f"concat failed (exit {result.returncode}):\n{result.stderr[-600:]}"
        )


async def stitch_film(
    clip_urls: list[str],
    *,
    outro_card: dict[str, Any] | None = None,
    outro_music_path: str | None = None,
    target_width: int = 720,
    target_height: int = 1280,
    target_fps: int = 30,
) -> str:
    """End-to-end stitch. Downloads clips, blends with xfade, layers outro
    music if supplied, appends outro card if supplied, returns final mp4
    path on local disk."""
    work = f"/tmp/tabloid_drama_{uuid.uuid4().hex[:8]}"
    os.makedirs(work, exist_ok=True)

    local_clips: list[str] = []
    for i, url in enumerate(clip_urls):
        path = os.path.join(work, f"clip_{i:02d}.mp4")
        await download_file(url, path)
        # blend_clips_with_xfade does an acrossfade across every clip's audio
        # stream; a clip with no audio (e.g. Seedance audio-safety retry path
        # returns generate_audio=False) breaks the chain (exit 234). Mux a
        # silent audio track into any clip that lacks one.
        if not _has_audio_stream(path):
            log.warning("clip %d has no audio stream — adding silence", i)
            dur = probe_duration(path) or 5.0
            with_audio = os.path.join(work, f"clip_{i:02d}_a.mp4")
            cmd = [
                "ffmpeg", "-y", "-hide_banner", "-loglevel", "error",
                "-i", path,
                "-f", "lavfi", "-t", f"{dur:.2f}",
                "-i", "anullsrc=r=48000:cl=stereo",
                "-shortest",
                "-c:v", "copy",
                "-c:a", "aac", "-b:a", "128k", "-ar", "48000", "-ac", "2",
                "-movflags", "+faststart",
                with_audio,
            ]
            r = subprocess.run(cmd, capture_output=True, text=True)
            if r.returncode != 0:
                log.warning(
                    "silent-audio mux failed for clip %d (%s) — using original",
                    i, r.stderr[-200:],
                )
            else:
                path = with_audio
        local_clips.append(path)

    blended = os.path.join(work, "blended.mp4")
    if len(local_clips) == 1:
        # xfade needs ≥2 clips; just copy the one clip through.
        subprocess.run(
            ["ffmpeg", "-y", "-hide_banner", "-loglevel", "error",
             "-i", local_clips[0],
             "-vf", f"scale={target_width}:{target_height}:force_original_aspect_ratio=decrease,"
                    f"pad={target_width}:{target_height}:(ow-iw)/2:(oh-ih)/2,"
                    f"setsar=1,fps={target_fps},format=yuv420p",
             "-c:v", "libx264", "-preset", "veryfast", "-crf", "20",
             "-c:a", "aac", "-b:a", "192k", "-ar", "48000", "-ac", "2",
             "-movflags", "+faststart",
             blended],
            check=True,
        )
    else:
        blend_clips_with_xfade(
            local_clips,
            output_path=blended,
            xfade_duration=0.15,
            transition="fade",
            target_width=target_width,
            target_height=target_height,
            target_fps=target_fps,
        )

    # Music overlay (optional). overlay_music handles the no-music case
    # via stream copy.
    with_music = os.path.join(work, "with_music.mp4")
    overlay_music(
        video_path=blended,
        output_path=with_music,
        outro_music=outro_music_path if outro_music_path and os.path.exists(outro_music_path) else None,
        outro_overlap_seconds=2.5,
        music_volume=0.55,
        mix_volume=1.4,
    )

    # Outro card (optional)
    if outro_card and outro_card.get("text"):
        card_path = os.path.join(work, "outro_card.mp4")
        card_dur = max(4.0, float(outro_card.get("duration_s", 4.0)))
        _render_outro_card(
            outro_card["text"],
            card_dur,
            target_width, target_height, target_fps,
            card_path,
        )
        final = os.path.join(work, "final.mp4")
        _concat([with_music, card_path], final)
        log.info(
            "drama editor: final film %.1fs (with %d clips + outro card)",
            probe_duration(final), len(local_clips),
        )
        return final

    log.info(
        "drama editor: final film %.1fs (with %d clips, no outro card)",
        probe_duration(with_music), len(local_clips),
    )
    return with_music
